set -g history-limit 10000
# -- Suporte ao mouse --
set -g mouse on
# -- Keybindings do modo de cópia --
set -g mode-keys vi
# -- Permite cópia para área de transferência --
set -g set-clipboard on
# É necessário instalar o xclip (Linux) ou pbcopy (Mac)
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
